"""Add faction_id to groups table

Revision ID: 00d657b4b1f5
Revises: remove_old_roles_column
Create Date: 2025-09-03 22:34:09.494521

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00d657b4b1f5"
down_revision = "remove_old_roles_column"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ability", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=15),
            type_=sa.Enum(
                "generic",
                "starting_skills",
                "skill_discounts",
                "group_income",
                "starting_item",
                "starting_reputation",
                name="abilitytype",
                native_enum=False,
            ),
            existing_nullable=False,
        )
        batch_op.create_foreign_key(
            "fk_ability_starting_reputation_faction",
            "faction",
            ["starting_reputation_faction_id"],
            ["id"],
        )

    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.add_column(sa.Column("faction_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_group_faction", "faction", ["faction_id"], ["id"])

    # Set a default faction for existing groups (assuming faction with id=1 exists)
    # This will need to be adjusted based on your actual faction data
    op.execute("UPDATE `group` SET faction_id = 1 WHERE faction_id IS NULL")

    # Now make the column NOT NULL
    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.alter_column("faction_id", nullable=False)

    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_skill_adds_reputation_faction", "faction", ["adds_reputation_faction_id"], ["id"]
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=255),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=128),
            nullable=True,
        )

    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.drop_constraint("fk_skill_adds_reputation_faction", type_="foreignkey")

    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.drop_constraint("fk_group_faction", type_="foreignkey")
        batch_op.drop_column("faction_id")

    with op.batch_alter_table("ability", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ability_starting_reputation_faction", type_="foreignkey")
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "generic",
                "starting_skills",
                "skill_discounts",
                "group_income",
                "starting_item",
                "starting_reputation",
                name="abilitytype",
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=15),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
