"""update_event_type_enum_remove_sanctioned_add_sanctioned_continuity_and_sanctioned_chronicle

Revision ID: 374c132bbe1d
Revises: ead2c222c7b1
Create Date: 2025-07-28 13:29:31.065713

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "374c132bbe1d"
down_revision = "ead2c222c7b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First, update any existing 'sanctioned' events to 'sanctioned-continuity'
    # fmt: off
    op.execute(
        "UPDATE events SET event_type = 'sanctioned-continuity' "
        "WHERE event_type = 'sanctioned'"
    )
    # fmt: on

    # Update the enum type to include the new values
    # We need to create a new enum with the updated values
    op.execute("ALTER TYPE eventtype RENAME TO eventtype_old")

    # Create the new enum with updated values
    op.execute(
        "CREATE TYPE eventtype AS ENUM "
        "('mainline', 'sanctioned-continuity', 'sanctioned-chronicle', 'online')"
    )

    # Update the column to use the new enum type
    op.execute(
        "ALTER TABLE events ALTER COLUMN event_type TYPE eventtype "
        "USING event_type::text::eventtype"
    )

    # Drop the old enum
    op.execute("DROP TYPE eventtype_old")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # fmt: off
    # First, update any 'sanctioned-continuity' and 'sanctioned-chronicle'
    # events back to 'sanctioned'
    op.execute(
        "UPDATE events SET event_type = 'sanctioned' "
        "WHERE event_type IN ('sanctioned-continuity', 'sanctioned-chronicle')"
    )
    # fmt: on

    # Update the enum type back to the original values
    op.execute("ALTER TYPE eventtype RENAME TO eventtype_new")

    # Create the old enum with original values
    op.execute("CREATE TYPE eventtype AS ENUM ('mainline', 'sanctioned', 'online')")

    # Update the column to use the old enum type
    op.execute(
        "ALTER TABLE events ALTER COLUMN event_type TYPE eventtype "
        "USING event_type::text::eventtype"
    )

    # Drop the new enum
    op.execute("DROP TYPE eventtype_new")

    # ### end Alembic commands ###
