"""Add character inventory and item transfer request models

Revision ID: 3cb76b9b8e3a
Revises: 4722e2d66da5
Create Date: 2025-07-28 21:31:31.872881

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3cb76b9b8e3a"
down_revision = "4722e2d66da5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "item_id", name="uix_character_item"),
    )
    op.create_table(
        "item_transfer_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requesting_character_id", sa.Integer(), nullable=False),
        sa.Column("target_character_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "denied", name="itemtransferstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("processed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["processed_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requesting_character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_character_id"],
            ["character.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_transfer_request_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transfer_request_id", sa.Integer(), nullable=False),
        sa.Column("character_item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_item_id"],
            ["character_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_request_id"],
            ["item_transfer_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_transfer_request_items")
    op.drop_table("item_transfer_requests")
    op.drop_table("character_items")
    # ### end Alembic commands ###
