"""add_item_version_and_printed_fields

Revision ID: 49ae29baa047
Revises: 70c27f96bd03
Create Date: 2025-07-29 15:07:24.238423

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49ae29baa047"
down_revision = "70c27f96bd03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.add_column(
        "item", sa.Column("printed", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "printed")
    op.drop_column("item", "version")
    # ### end Alembic commands ###
