"""add_group_background_fields_and_join_requests

Revision ID: 4f1a135f8b36
Revises: 81e586ec00bb
Create Date: 2025-07-31 14:47:29.140118

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "4f1a135f8b36"
down_revision = "81e586ec00bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if tables already exist to avoid conflicts
    inspector = inspect(op.get_bind())
    existing_tables = inspector.get_table_names()

    if "group_backgrounds" not in existing_tables:
        op.create_table(
            "group_backgrounds",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("group_id", sa.Integer(), nullable=False),
            sa.Column("background", sa.Text(), nullable=True),
            sa.Column("objective", sa.Text(), nullable=True),
            sa.Column("goals", sa.Text(), nullable=True),
            sa.Column("needs_review", sa.Boolean(), nullable=False),
            sa.Column("reviewed_at", sa.DateTime(), nullable=True),
            sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["group_id"],
                ["group.id"],
            ),
            sa.ForeignKeyConstraint(
                ["reviewed_by_user_id"],
                ["user.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )

    if "group_join_requests" not in existing_tables:
        op.create_table(
            "group_join_requests",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("group_id", sa.Integer(), nullable=False),
            sa.Column("character_id", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("reviewed_at", sa.DateTime(), nullable=True),
            sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["character_id"],
                ["character.id"],
            ),
            sa.ForeignKeyConstraint(
                ["group_id"],
                ["group.id"],
            ),
            sa.ForeignKeyConstraint(
                ["reviewed_by_user_id"],
                ["user.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "group_id", "character_id", name="uix_group_character_join_request"
            ),
        )
    with op.batch_alter_table("ability", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_ability_starting_item_blueprint",
            "item_blueprints",
            ["starting_item_blueprint_id"],
            ["id"],
        )

    # Check if columns already exist in group table
    group_columns = [col["name"] for col in inspector.get_columns("group")]

    with op.batch_alter_table("group", schema=None) as batch_op:
        if "background" not in group_columns:
            batch_op.add_column(sa.Column("background", sa.Text(), nullable=True))
        if "objective" not in group_columns:
            batch_op.add_column(sa.Column("objective", sa.Text(), nullable=True))
        if "goals" not in group_columns:
            batch_op.add_column(sa.Column("goals", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.drop_column("goals")
        batch_op.drop_column("objective")
        batch_op.drop_column("background")

    with op.batch_alter_table("ability", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ability_starting_item_blueprint", type_="foreignkey")

    op.drop_table("group_join_requests")
    op.drop_table("group_backgrounds")
    # ### end Alembic commands ###
