"""add_player_other_field_to_downtime_packs

Revision ID: 70c27f96bd03
Revises: merge_reputation_briefings_heads
Create Date: 2025-07-29 14:00:11.415953

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70c27f96bd03"
down_revision = "merge_reputation_briefings_heads"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downtime_packs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("player_other", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downtime_packs", schema=None) as batch_op:
        batch_op.drop_column("player_other")
    # ### end Alembic commands ###
