"""add_item_audit_log_table

Revision ID: 81e586ec00bb
Revises: 49ae29baa047
Create Date: 2025-07-29 15:15:24.238423

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81e586ec00bb"
down_revision = "49ae29baa047"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("editor_user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "edit",
                "version_increment",
                "printed",
                "mods_changed",
                "expiry_changed",
                "blueprint_changed",
                name="itemauditaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("changes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["editor_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_audit_log")
    # ### end Alembic commands ###
