"""Add reputation briefings tables

Revision ID: add_reputation_briefings_tables
Revises: merge_heads
Create Date: 2025-01-27 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_reputation_briefings_tables"
down_revision = "merge_heads"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reputation_briefings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("faction_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "incomplete",
                "submitted",
                "discarded",
                name="reputationbriefingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["faction_id"],
            ["faction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reputation_briefing_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("briefing_id", sa.Integer(), nullable=False),
        sa.Column("reputation_required", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["briefing_id"],
            ["reputation_briefings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Add notify_reputation_briefing column to user table
    op.add_column(
        "user",
        sa.Column("notify_reputation_briefing", sa.Boolean(), nullable=True, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "notify_reputation_briefing")
    op.drop_table("reputation_briefing_levels")
    op.drop_table("reputation_briefings")
    # ### end Alembic commands ###
