"""add description to mods

Revision ID: add_description_to_mods
Revises: 3cb76b9b8e3a
Create Date: 2024-01-15 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_description_to_mods"
down_revision = "3cb76b9b8e3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mods", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mods", "description")
    # ### end Alembic commands ###
