"""add_credits_added_to_downtime_packs

Revision ID: b4ddf1331b0f
Revises: bc27aa9aa916
Create Date: 2025-12-08 13:59:35.959951

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4ddf1331b0f"
down_revision = "bc27aa9aa916"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downtime_packs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credits_added", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downtime_packs", schema=None) as batch_op:
        batch_op.drop_column("credits_added")
    # ### end Alembic commands ###
