"""add subtype and ability fields to item blueprints

Revision ID: bc27aa9aa916
Revises: 00d657b4b1f5
Create Date: 2025-09-24 17:51:17.943261

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc27aa9aa916"
down_revision = "00d657b4b1f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_blueprints", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtype", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("ability", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_blueprints", schema=None) as batch_op:
        batch_op.drop_column("ability")
        batch_op.drop_column("subtype")

    # ### end Alembic commands ###
