"""Add pack system, global settings, group type model, and related changes

Revision ID: dcfca26159fc
Revises: b4a1290dd816
Create Date: 2025-06-24 09:55:31.113693

"""

from datetime import datetime, timedelta

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "dcfca26159fc"
down_revision = "b4a1290dd816"
branch_labels = None
depends_on = None


def upgrade():
    # Check which tables already exist
    inspector = inspect(op.get_bind())
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if "global_settings" not in existing_tables:
        op.create_table(
            "global_settings",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("character_income_ec", sa.Integer(), nullable=False),
            sa.Column("group_income_contribution", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    if "group_types" not in existing_tables:
        op.create_table(
            "group_types",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("description", sa.Text(), nullable=False),
            sa.Column("income_items", sa.String(), nullable=True),
            sa.Column("income_items_discount", sa.Float(), nullable=False),
            sa.Column("income_substances", sa.Boolean(), nullable=False),
            sa.Column("income_substance_cost", sa.Integer(), nullable=False),
            sa.Column("income_medicaments", sa.Boolean(), nullable=False),
            sa.Column("income_medicament_cost", sa.Integer(), nullable=False),
            sa.Column("income_distribution", sa.String(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )

    # Drop tables only if they exist
    if "user_roles" in existing_tables:
        op.drop_table("user_roles")
    if "role" in existing_tables:
        op.drop_table("role")

    # Add columns to existing tables
    if "ability" in existing_tables:
        ability_columns = [col["name"] for col in inspector.get_columns("ability")]
        if "additional_group_income" not in ability_columns:
            with op.batch_alter_table("ability", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column("additional_group_income", sa.Integer(), nullable=True)
                )

    if "character" in existing_tables:
        character_columns = [col["name"] for col in inspector.get_columns("character")]
        if "pack_complete" not in character_columns:
            with op.batch_alter_table("character", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column(
                        "pack_complete", sa.Boolean(), nullable=False, server_default=sa.false()
                    )
                )
        if "character_pack" in character_columns:
            # Check if character_pack is JSON type and convert to String
            character_pack_col = next(
                col for col in inspector.get_columns("character") if col["name"] == "character_pack"
            )
            if "JSON" in str(character_pack_col["type"]):
                with op.batch_alter_table("character", schema=None) as batch_op:
                    batch_op.alter_column(
                        "character_pack",
                        existing_type=sqlite.JSON(),
                        type_=sa.String(),
                        existing_nullable=True,
                    )

    if "character_audit_log" in existing_tables:
        audit_log_columns = [col["name"] for col in inspector.get_columns("character_audit_log")]
        if "action" in audit_log_columns:
            action_col = next(
                col
                for col in inspector.get_columns("character_audit_log")
                if col["name"] == "action"
            )
            if "VARCHAR" in str(action_col["type"]):
                with op.batch_alter_table("character_audit_log", schema=None) as batch_op:
                    batch_op.alter_column(
                        "action",
                        existing_type=sa.VARCHAR(length=17),
                        type_=sa.Enum(
                            "create",
                            "edit",
                            "status_change",
                            "skill_change",
                            "reputation_change",
                            "funds_added",
                            "funds_removed",
                            "funds_set",
                            "group_joined",
                            "group_left",
                            "condition_change",
                            "cybernetics_change",
                            name="characterauditaction",
                            native_enum=False,
                        ),
                        existing_nullable=False,
                    )

    if "character_conditions" in existing_tables:
        conditions_columns = [col["name"] for col in inspector.get_columns("character_conditions")]
        if "current_stage" in conditions_columns:
            current_stage_col = next(
                col
                for col in inspector.get_columns("character_conditions")
                if col["name"] == "current_stage"
            )
            if not current_stage_col["nullable"]:
                with op.batch_alter_table("character_conditions", schema=None) as batch_op:
                    batch_op.alter_column(
                        "current_stage", existing_type=sa.INTEGER(), nullable=True
                    )

    # Fix for SQLite NOT NULL column issue: Add booking_deadline as nullable first
    if "events" in existing_tables:
        events_columns = [col["name"] for col in inspector.get_columns("events")]
        if "booking_deadline" not in events_columns:
            with op.batch_alter_table("events", schema=None) as batch_op:
                batch_op.add_column(sa.Column("booking_deadline", sa.DateTime(), nullable=True))

            # Update existing events to set booking_deadline to early_booking_deadline + 10 days
            connection = op.get_bind()
            events = connection.execute(
                sa.text(
                    "SELECT id, early_booking_deadline FROM events WHERE booking_deadline IS NULL"
                )
            )
            for event in events:
                early_deadline = datetime.fromisoformat(
                    event.early_booking_deadline.replace("Z", "+00:00")
                )
                booking_deadline = early_deadline + timedelta(days=10)
                connection.execute(
                    sa.text(
                        "UPDATE events SET booking_deadline = :booking_deadline "
                        "WHERE id = :event_id"
                    ),
                    {"booking_deadline": booking_deadline.isoformat(), "event_id": event.id},
                )

            # Now make the column NOT NULL
            with op.batch_alter_table("events", schema=None) as batch_op:
                batch_op.alter_column("booking_deadline", nullable=False)

    if "group" in existing_tables:
        group_columns = [col["name"] for col in inspector.get_columns("group")]
        if "group_type_id" not in group_columns:
            with op.batch_alter_table("group", schema=None) as batch_op:
                batch_op.add_column(sa.Column("group_type_id", sa.Integer(), nullable=False))
        if "group_pack" not in group_columns:
            with op.batch_alter_table("group", schema=None) as batch_op:
                batch_op.add_column(sa.Column("group_pack", sa.String(), nullable=True))
        if "pack_complete" not in group_columns:
            with op.batch_alter_table("group", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column(
                        "pack_complete", sa.Boolean(), nullable=False, server_default=sa.false()
                    )
                )

        # Add foreign key if it doesn't exist
        if "group_types" in existing_tables:
            foreign_keys = inspector.get_foreign_keys("group")
            fk_exists = any(fk["referred_table"] == "group_types" for fk in foreign_keys)
            if not fk_exists:
                with op.batch_alter_table("group", schema=None) as batch_op:
                    batch_op.create_foreign_key(
                        "fk_group_group_type_id", "group_types", ["group_type_id"], ["id"]
                    )

        # Drop old columns if they exist
        if "pack_data" in group_columns:
            with op.batch_alter_table("group", schema=None) as batch_op:
                batch_op.drop_column("pack_data")
        if "type" in group_columns:
            with op.batch_alter_table("group", schema=None) as batch_op:
                batch_op.drop_column("type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    existing_tables = inspector.get_table_names()

    if "group" in existing_tables:
        group_columns = [col["name"] for col in inspector.get_columns("group")]
        with op.batch_alter_table("group", schema=None) as batch_op:
            if "type" not in group_columns:
                batch_op.add_column(sa.Column("type", sa.VARCHAR(length=10), nullable=False))
            if "pack_data" not in group_columns:
                batch_op.add_column(sa.Column("pack_data", sa.TEXT(), nullable=True))

            # Drop foreign key if it exists
            foreign_keys = inspector.get_foreign_keys("group")
            fk_name = None
            for fk in foreign_keys:
                if (
                    fk["referred_table"] == "group_types"
                    and "group_type_id" in fk["constrained_columns"]
                ):
                    fk_name = fk["name"]
                    break
            if fk_name:
                batch_op.drop_constraint(fk_name, type_="foreignkey")

            if "pack_complete" in group_columns:
                batch_op.drop_column("pack_complete")
            if "group_pack" in group_columns:
                batch_op.drop_column("group_pack")
            if "group_type_id" in group_columns:
                batch_op.drop_column("group_type_id")

    if "events" in existing_tables:
        events_columns = [col["name"] for col in inspector.get_columns("events")]
        if "booking_deadline" in events_columns:
            with op.batch_alter_table("events", schema=None) as batch_op:
                batch_op.drop_column("booking_deadline")

    if "character_conditions" in existing_tables:
        conditions_columns = [col["name"] for col in inspector.get_columns("character_conditions")]
        if "current_stage" in conditions_columns:
            current_stage_col = next(
                col
                for col in inspector.get_columns("character_conditions")
                if col["name"] == "current_stage"
            )
            if current_stage_col["nullable"]:
                with op.batch_alter_table("character_conditions", schema=None) as batch_op:
                    batch_op.alter_column(
                        "current_stage", existing_type=sa.INTEGER(), nullable=False
                    )

    if "character_audit_log" in existing_tables:
        audit_log_columns = [col["name"] for col in inspector.get_columns("character_audit_log")]
        if "action" in audit_log_columns:
            action_col = next(
                col
                for col in inspector.get_columns("character_audit_log")
                if col["name"] == "action"
            )
            if "Enum" in str(action_col["type"]):
                with op.batch_alter_table("character_audit_log", schema=None) as batch_op:
                    batch_op.alter_column(
                        "action",
                        existing_type=sa.Enum(
                            "create",
                            "edit",
                            "status_change",
                            "skill_change",
                            "reputation_change",
                            "funds_added",
                            "funds_removed",
                            "funds_set",
                            "group_joined",
                            "group_left",
                            "condition_change",
                            "cybernetics_change",
                            name="characterauditaction",
                            native_enum=False,
                        ),
                        type_=sa.VARCHAR(length=17),
                        existing_nullable=False,
                    )

    if "character" in existing_tables:
        character_columns = [col["name"] for col in inspector.get_columns("character")]
        with op.batch_alter_table("character", schema=None) as batch_op:
            if "character_pack" in character_columns:
                character_pack_col = next(
                    col
                    for col in inspector.get_columns("character")
                    if col["name"] == "character_pack"
                )
                if "String" in str(character_pack_col["type"]):
                    batch_op.alter_column(
                        "character_pack",
                        existing_type=sa.String(),
                        type_=sqlite.JSON(),
                        existing_nullable=True,
                    )
            if "pack_complete" in character_columns:
                batch_op.drop_column("pack_complete")

    if "ability" in existing_tables:
        ability_columns = [col["name"] for col in inspector.get_columns("ability")]
        if "additional_group_income" in ability_columns:
            with op.batch_alter_table("ability", schema=None) as batch_op:
                batch_op.drop_column("additional_group_income")

    if "user_roles" not in existing_tables:
        op.create_table(
            "user_roles",
            sa.Column("user_id", sa.INTEGER(), nullable=False),
            sa.Column("role_id", sa.INTEGER(), nullable=False),
            sa.ForeignKeyConstraint(
                ["role_id"],
                ["role.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["user.id"],
            ),
            sa.PrimaryKeyConstraint("user_id", "role_id"),
        )
    if "role" not in existing_tables:
        op.create_table(
            "role",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("name", sa.VARCHAR(length=20), nullable=False),
            sa.Column("description", sa.VARCHAR(length=100), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )
    if "group_types" in existing_tables:
        op.drop_table("group_types")
    if "global_settings" in existing_tables:
        op.drop_table("global_settings")
    # ### end Alembic commands ###
