"""add_group_audit_log_table

Revision ID: df727425156a
Revises: 464f5fdf68a5
Create Date: 2025-06-23 20:13:42.978721

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df727425156a"
down_revision = "464f5fdf68a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("editor_user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "edit",
                "member_added",
                "member_removed",
                "member_left",
                "funds_added",
                "funds_withdrawn",
                "disbanded",
                "invite_sent",
                "invite_declined",
                name="groupauditaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("changes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["editor_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_audit_log")
    # ### end Alembic commands ###
