"""Add other field to downtime packs

Revision ID: e43a060cc670
Revises: 374c132bbe1d
Create Date: 2025-07-28 14:25:01.420511

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e43a060cc670"
down_revision = "374c132bbe1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.alter_column(
            "character_pack", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=True
        )

    with op.batch_alter_table("downtime_packs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("other", sa.JSON(), nullable=True))

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column(
            "event_type",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                "mainline",
                "sanctioned-continuity",
                "sanctioned-chronicle",
                "online",
                name="eventtype",
                native_enum=False,
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column(
            "event_type",
            existing_type=sa.Enum(
                "mainline",
                "sanctioned-continuity",
                "sanctioned-chronicle",
                "online",
                name="eventtype",
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("downtime_packs", schema=None) as batch_op:
        batch_op.drop_column("other")

    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.alter_column(
            "character_pack", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=True
        )

    # ### end Alembic commands ###
