name: Delete Branch on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    name: Delete Source Branch
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${context.payload.pull_request.head.ref}`
              });
              console.log(`Successfully deleted branch: ${context.payload.pull_request.head.ref}`);
            } catch (error) {
              console.log(`Branch ${context.payload.pull_request.head.ref} was already deleted or doesn't exist`);
            }
