name: Initial Repository Setup

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/initial-setup.yml'

jobs:
  setup-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Set up branch protection for master
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'master',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'Tests and Linting',
                    'Security Checks',
                    'Pre-commit Checks'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              console.log('✅ Branch protection enabled for master');
            } catch (error) {
              console.error('❌ Error setting up branch protection for master:', error.message);
            }

      - name: Setup Repository Settings
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Update repository settings
              await github.rest.repos.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                allow_merge_commit: true,
                allow_squash_merge: true,
                allow_rebase_merge: false,
                delete_branch_on_merge: true,
                has_issues: true,
                has_wiki: false,
                has_projects: false
              });
              console.log('✅ Repository settings updated');
            } catch (error) {
              console.error('❌ Error updating repository settings:', error.message);
            }

      - name: Create Issue Templates
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Check if issue templates directory exists
              const contents = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: '.github/ISSUE_TEMPLATE'
              });
              console.log('ℹ️  Issue templates already exist');
            } catch (error) {
              if (error.status === 404) {
                console.log('ℹ️  No issue templates found, consider adding them for better issue management');
              } else {
                console.error('❌ Error checking issue templates:', error.message);
              }
            }
