name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  required-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov flake8 black isort

    - name: Run linting checks
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        black --check --diff .
        isort --check-only --diff .

    - name: Run tests
      run: |
        pytest --cov=. --cov-report=term-missing --cov-fail-under=70

    - name: Check test coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-fail-under=70
