name: Setup Branch Protection

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/setup-branch-protection.yml'

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch Protection for master
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'master',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'Tests and Linting',
                    'Security Checks', 
                    'Pre-commit Checks'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              console.log('Branch protection enabled for master');
            } catch (error) {
              console.error('Error setting up branch protection for master:', error.message);
            }

      - name: Setup Branch Protection for develop
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'develop',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'Tests and Linting',
                    'Security Checks', 
                    'Pre-commit Checks'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              console.log('Branch protection enabled for develop');
            } catch (error) {
              console.error('Error setting up branch protection for develop:', error.message);
            } 